version: "2"

services:
  elasticsearch:
    image: elasticsearch:5.6.8
    ports:
    - 9200:9200
    environment:
    - "cluster.name=applog"
  cerebro:
    image: dylanmei/cerebro
    ports:
    - 9000:9000
    command:
    - bin/cerebro
    - -Dhosts.0.host=http://elasticsearch:9200


